### ISSUE TITLE
Entropy model in Cheng2020Anchor

### ISSUE THREAD

**Issue by Lithium07** [InterDigitalInc/CompressAI#11]
Firstly, thanks authors for sharing the amazing work. I have a question about the Cheng2020Anchor model. In Cheng's original paper, the discretized Gaussian mixture likelihood is used where three Gaussian distributions are weighted. However, I find that the Cheng2020Anchor model still uses the single Gaussian distribution in JointAutoregressiveHierarchicalPriors. Is my understanding right? Thanks

**Comment by jbegaint** [comment]
Hi, yes we have only implemented the "anchor" model and the "anchor" model with the attention layers for now. We might implement the full version with the GMM based entropy model later in the future.

**Comment by qiusuor** [comment]
Thanks for nice work. Also waiting for implementation of Gaussian mixture likelihood.

**Comment by Lithium07** [comment]
Thanks for clarifying it.
