### ISSUE TITLE
Usage of QReLU

### ISSUE THREAD

**Issue by Lithium07** [InterDigitalInc/CompressAI#117]
Thanks for releasing the code of the video model ssf. I found that, in the Hyperprior model, the mean and scale use separate hyper decoders, and the scale decoder uses the QReLU function. The QReLU is originally designed for integral compression network in Google's paper. Is there any reason for using separate decoders and the QReLU (only used in the scale decoder) for the video codec? Hope to get your sharing and insight. Thanks a lot.

**Comment by Lithium07** [comment]
And the bit_depth is set as 8, why not 1?
![image](https://user-images.githubusercontent.com/26594195/150270963-3096d060-e2b1-4178-a503-7407de233da7.png)

**Comment by chyomin06** [comment]
Hi, 

I think it is good to have a discussion on the Discussion page.
Please, see this (https://github.com/InterDigitalInc/CompressAI/discussions/118)

Thank you.
