### ISSUE TITLE
Dataset Professional CLIC and mobile CLIC

### ISSUE THREAD

**Issue by ntphuc0101** [InterDigitalInc/CompressAI#122]
Dear madam or sir,
In the result section -https://github.com/InterDigitalInc/CompressAI/tree/master/results, I have a question about CLIC professional and mobile CLIC mobile whether they are belonging to testing or training or validation.?
Thank you very much.
Kind Regards,
Nguyen Thai Vinh, Phuc

**Comment by fracape** [comment]
Hi. Sorry for the late reply. The results correspond to the test sets.
