### ISSUE TITLE
 Uninitialized CDFs. Run update() first

### ISSUE THREAD

**Issue by zjnlxk** [InterDigitalInc/CompressAI#141]
First of all, thank you for your work.

I trained a model (cheng2020-attn) on my own dataset and then tried to do some tests with your evaluation script.

I just trained a model (cheng2020-attn) on my own dataset.
python3 train.py -d $DATASET --epochs 100 -lr 1e-4 --batch-size 16 --cuda --save

python -m compressai.utils.update_model --architecture cheng2020-attn weight/cheng2020-attn/checkpoint_best_loss.pth.tar 

python -m compressai.utils.eval_model  checkpoint crop_img -a cheng2020-attn  -p weight/cheng2020-attn/checkpoint_best_loss.pth.tar

Then I got an error
KeyError: 'g_a.0.weight'

next, I extracted the state_dict key from the checkpoint.

Execute the following command again

python -m compressai.utils.update_model --architecture cheng2020-attn weight/cheng2020-attn/checkpoint_best_loss.pth.tar 

python -m compressai.utils.eval_model  checkpoint crop_img -a cheng2020-attn  -p weight/cheng2020-attn/checkpoint_best_loss.pth.tar

finally , I met the error 

Uninitialized CDFs. Run update() first!

where should i modify for update?

The documentation link mentioned in the other issue, when I click it, I get a 404 not found
https://interdigitalinc.github.io/CompressAI/tutorial_train.html#updating-the-model).

**Comment by johnli25** [comment]
Hi, any update on this issue? I see you marked as closed/completed, but you didn't provide any solution/update.
