### ISSUE TITLE
How many epochs did you use during the training process?

### ISSUE THREAD

**Issue by tahsirmunna** [InterDigitalInc/CompressAI#143]
Dear Authors,

Thank you for your brilliant work. I am going to use your code and pre-train codec. During training the codec with the [Jpegai dataset](https://jpegai.github.io/3-datasets/) and [Vimeo90k triple dataset](http://toflow.csail.mit.edu/), I did not get the same result that you [showed in the description](https://interdigitalinc.github.io/CompressAI/zoo.html#all-models). I have read and carefully applied all the parameters that you used during the training process. But still, I am losing the quality of the images.

Here, I have mentioned my training parameters,

```
Loss function: mse
learning rate: 1e-5
epochs: 100
lambda: 0.0130
batch-size: 16
rest of parameters are default
```

So, how many epochs did you use during the training process?

Thank you

I have attached a plot for understanding my results well ( this result is only for model 4 ( quality=4)
![vimeo90k_final_result](https://user-images.githubusercontent.com/9991209/172414183-eb80ade9-34a1-43e3-baec-2d667951b4d8.png)

**Comment by fracape** [comment]
That's right, thanks @tahsirmunna. We set max 500 but the number of epochs varies since it is terminated early when there is no improvement over several epochs.

**Comment by tahsirmunna** [comment]
Thank you very much @fracape

**Comment by tzayuan** [comment]
Hi, @tahsirmunna:

I would like to ask you two questions:
1. Where are the descriptions and parameter records related to the official training process?
2. When you train on the vimeo dataset, do you use the official trained model to continue training, or do you start from scratch to ensure the controllability of the model?

Thank you.

BRs
tzayuan
