### ISSUE TITLE
GMM moduls is not used in cheng2020-anchor?

### ISSUE THREAD

**Issue by ywz978020607** [InterDigitalInc/CompressAI#15]
Excuse me, I saw the  cheng2020-anchor code and found that the entropy model is used with a single Gaussion model, but in the author paper, the Gaussion Mixture Model (GMM) is used, could you fresh these code? Thanks~

**Comment by jbegaint** [comment]
Hi, yes we have only implemented the "anchor" model and the "anchor" model with the attention layers for now. We might implement the full version with the GMM based entropy model later in the future.

**Comment by ywz978020607** [comment]
I have achieved these part, including GMM model with Range Coder.
https://www.cnblogs.com/sharklet/p/12809114.html
