### ISSUE TITLE
  ValueError: path '/home/runner/work/CompressAI/CompressAI/compressai/cpp_exts/ops/ops.cpp' cannot be absolute

### ISSUE THREAD

**Issue by zzm422** [InterDigitalInc/CompressAI#152]
## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from `python3 -m torch.utils.collect_env`

```
- PyTorch / CompressAI Version (e.g., 1.0 / 0.4.0):
- OS (e.g., Linux):
- How you installed PyTorch / CompressAI (`pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:
```

**Comment by umbertov** [comment]
same problem here (only on windows), did you find a solution?

**Comment by fracape** [comment]
Hi, your description of the bug is very succinct. However, it seems to be the link with your c++ compiler. We tested tested with gcc and clang only.  Please look up the list of  previous issues here, a couple of them relate to that.

**Comment by Yiozolm** [comment]
I try to install by run 'python setup.py install' and face the same situation.
You can find SOURCES.txt under the compressai.egg-info
![2](https://github.com/InterDigitalInc/CompressAI/assets/59084547/a810f36c-7c29-40cf-8684-60a95b9ea37a)
and correct the wrong path in this file.(the red circle in png file)
![1](https://github.com/InterDigitalInc/CompressAI/assets/59084547/e27d3000-6f32-4949-98c0-f5bf7b71221d)
Once you succeed in solving require, it is installed.
