### ISSUE TITLE
transplant third_party/ryg_rans/rans64.h into Android 64-bit devices: rans64.h error: __int128 is not supported on this target

### ISSUE THREAD

**Issue by swaiwi** [InterDigitalInc/CompressAI#158]
## Bug

When I transplant third_party/ryg_rans/rans64.h into Android 64-bit devices, I got such error as:
thirdparty\ryg_rans\rans64.h:44:35: error: __int128 is not supported on this target.
How can I modify this code to support it on arm device?

**Comment by fracape** [comment]
Hi, we directly use the rANS as is. Please refer to https://github.com/rygorous/ryg_rans for its usage and reporting compatibility issues.
