### ISSUE TITLE
Problem when I download compressai with pip 

### ISSUE THREAD

**Issue by AlbertoPresta** [InterDigitalInc/CompressAI#160]
## Bug

Hi, first of all thanks for your precious work, amazing. 
Recently I tried to download your repository via the command "pip install compressai", and it failed. It seemed that it is not a problem of pip: it is possible that it is a problem of setup requirements, 

OS: WIndows 11
PC: Inspiron 14 5410 
Processor: 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz   1.80 GHz 
Python: Python 3.8.8
Gcc compiler: g++ (GCC) 11.2.0

In the following screen I report the bug.

<img width="941" alt="Immagine 2022-09-10 112533" src="https://user-images.githubusercontent.com/43781044/189477476-f92c56a0-c629-4919-bb07-7e2eb8f454e8.png">

1. open terminal
2. pip install compressai 

## Environment

Please copy and paste the output from `python3 -m torch.utils.collect_env`

Collecting environment information...
PyTorch version: 1.12.1+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: (GCC) 11.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.2
[pip3] torch==1.12.1
[conda] Could not collect

**Comment by YodaEmbedding** [comment]
Does the ["Installation from source"](https://github.com/InterDigitalInc/CompressAI#installation) work?

**Comment by AlbertoPresta** [comment]
it does not work (same problem)

**Comment by YodaEmbedding** [comment]
Does it give a different error? Also, try this:

```bash
git clone https://github.com/InterDigitalInc/CompressAI compressai
cd compressai

python3 -m venv venv
source venv/bin/activate
pip install -U pip && pip install -e .
```

**Comment by AlbertoPresta** [comment]
I yes, same error.
I have tried the follwing command


git clone https://github.com/InterDigitalInc/CompressAI compressai
cd compressai

python3 -m venv venv
source venv/bin/activate
pip install -U pip && pip install -e .

when I run python -m vemv vemv  I got the following error

Error: 'list' object has no attribute 'read'

**Comment by YodaEmbedding** [comment]
Sounds like your Python installation might have issues. (Not CompressAI.)

Consider reinstalling Python, check which Python is being used (`which python3`), switching to WSL2/Docker/Conda/..., or maybe one of the suggestions here:


https://github.com/matterport/Mask_RCNN/issues/951#issuecomment-1000553128  
https://stackoverflow.com/questions/67937526/python-virtual-environments-error-list-object-has-no-attribute-read
