### ISSUE TITLE
Help: VTM Usage Issue

### ISSUE THREAD

**Issue by yifeipet** [InterDigitalInc/CompressAI#163]
I am trying to use VTM codec to encode an JPEG image and decode it. 
I am not very sure about the "-b" and "-c" arguments so I got errors. 
I use Colab to test the codes.
[https://colab.research.google.com/drive/1lxPfasLZnMwfd8GaO4y5eiC6aeAYvxca?usp=sharing](url)
I created one image folder under the compressai folder and uploaded one JPEG image into the image folder.
I also created a VTM_image folder and I need to save the compressed file and the decoded image. 

I have a big difficulty to figure out how to solve the errors. Can you see the codes and help me with the issues? Thank you!
------------------------------------------------------------------------------------
I got to know I need to download VTM software and then use the compressai codes. I will try to test it. Thank you!

**Comment by fracape** [comment]
Yes, please clone and build the software from https://vcgit.hhi.fraunhofer.de/jvet/VVCSoftware_VTM and then provide the path to EncoderAppStatic/DecoderAppStatic in your compressai.utils.bench command line
