### ISSUE TITLE
Support --recursive

### ISSUE THREAD

**Issue by Freed-Wu** [InterDigitalInc/CompressAI#173]
`python -m compressai.utils.eval_model pretrained -a mbt2018 {--recursive,-R} /mnt/ImageNet/val/` will eval subdirectories recursively.

**Comment by fracape** [comment]
done in [b1a4cae](https://github.com/InterDigitalInc/CompressAI/commit/b1a4cae1068cec96daa186f2e6c6b337a172dc77)
