### ISSUE TITLE
How to speed up encoding and decoding?

### ISSUE THREAD

**Issue by hot-dog** [InterDigitalInc/CompressAI#188]
Hi there, i have test cheng2020-anchor and mbt2018 model and found the encoding and decoding time cost is too high,  for 256x
256 image patch, the encoding time cost is 0.8s and decoding time cost is 2.2s. My computer hardware is as follows:
CPU: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
GPU: GeForce RTX 3090
Any adivce on how to speed up the encoding and decoding process?

**Comment by fracape** [comment]
Hi, this is a platform dedicated to research. These models use auto-regressive context modelling, which increase compression performance at the cost of sequential operations. There are newer papers improving this part, which can be  implemented.

**Comment by hot-dog** [comment]
Thank you very much for your reply, i got it, so it is just the algorithm's intrinsic shortcoming, not about the implementation. Issue closed.
