### ISSUE TITLE
get different kodak dataset testing result using VTM

### ISSUE THREAD

**Issue by linansheng** [InterDigitalInc/CompressAI#189]
I am trying to test kodak dataset use VTM codec with the command: python -m compressai.utils.bench vtm ./kodim -b ./VVCSoftware_VTM-VTM-9.1/bin -c ./VVCSoftware_VTM-VTM-9.1/cfg/encoder_intra_vtm.cfg -q 12 17 22 27 32 37 42 47 -j 24 >vtm9.1_kodim.json. But get different result with compressai's.  The bpp is almost the same, but psnr and msssim is worse then compressai's reult. Detailed result is attached. How can I get correct result?
[vtm9.1_kodim.txt](https://github.com/InterDigitalInc/CompressAI/files/10317896/vtm9.1_kodim.txt)

**Comment by YodaEmbedding** [comment]
Are you using the 768x512 sized Kodak dataset, like in CompressAI?

(There's also a full resolution 3072x2048 dataset, which gives different results.)

**Comment by linansheng** [comment]
yes, I am using orginal 768x512 or 512x768 images in Kodak dataset.  The testing Kodak images is attached. I am so confued about why the bpp is almost the same, but psnr is worse. I use vtm9.1 for testing, is it the same as compressAI?
[kodim.zip](https://github.com/InterDigitalInc/CompressAI/files/10318426/kodim.zip)

**Comment by linansheng** [comment]
> Are you using the 768x512 sized Kodak dataset, like in CompressAI?
> 
> (There's also a full resolution 3072x2048 dataset, which gives different results.)

yes, I am using orginal 768x512 or 512x768 images in Kodak dataset. If I use the dataset to test bpg or other pretrained deep image codec, I can get same results with CompressAI. I use vtm9.1 for testing, is it the same as CompressAI?

**Comment by wx-Tian** [comment]
I also encounted the same problem and the results are the same as you.How did you solve it?

**Comment by linansheng** [comment]
I didn't test with the script they provided latter. You can try convert png files into yuv format using ffmpeg, than bulid the VTM source code, use the executable file for coding and getting results.

**Comment by linansheng** [comment]
> I also encounted the same problem and the results are the same as you.How did you solve it?

I didn't test with the script they provided latter. You can try convert png files into yuv format using ffmpeg, than bulid the VTM source code, use the executable file for coding and getting results.

**Comment by wx-Tian** [comment]
Ok，thanks!!!



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 20, 2023 19:27 PM
To: ***@***.***&gt;;
Cc: "wenxin ***@***.******@***.***&gt;;
Subject: Re: [InterDigitalInc/CompressAI] get different kodak dataset testingresult using VTM (Issue #189)




  
I also encounted the same problem and the results are the same as you.How did you solve it?
  
I didn't test with the script they provided latter. You can try convert png files into yuv format using ffmpeg, than bulid the VTM source code, use the executable file for coding and getting results.

**Comment by paomian001** [comment]
> Are you using the 768x512 sized Kodak dataset, like in CompressAI?
> 
> (There's also a full resolution 3072x2048 dataset, which gives different results.)

May I ask how to calculate BPP after encoding some data using VTM?
