### ISSUE TITLE
ModuleNotFoundError: No module named 'compressai._CXX'

### ISSUE THREAD

**Issue by Zhenxing-Dong** [InterDigitalInc/CompressAI#197]
When I run "python -m compressai.utils.update_model --architecture bmshj2018-factorized checkpoint_best_loss.pth.tar“，I get the following error:
ModuleNotFoundError: No module named 'compressai._CXX'

Thank you very much!

**Comment by fracape** [comment]
Hi @Zhenxing-Dong,

Looks like you solved your issue and checked similar past threads. Could you post how you solved to help future developers. I think it's usually mismatching python version between the current one which pybind11 uses and and the one used to build c++ objects.
