### ISSUE TITLE
ImageFolder Function

### ISSUE THREAD

**Issue by Zhenxing-Dong** [InterDigitalInc/CompressAI#202]
Hello!

When I tried to modify the ImageFoloder function, I found that none of my actions could change it. I also tried to print some variables in the ImageFolder function, but that was also impossible.

I would really appreciate your help!

Thank you very much!

**Comment by fracape** [comment]
Did you install compressai from your sources, or from pypi (pip install compressai)?

**Comment by Zhenxing-Dong** [comment]
I followed this link "https://github.com/InterDigitalInc/CompressAI/issues/102#issuecomment-1039827082" to install compressai.

Is there any difference between the two approaches?

By the way, since I wanted to compress the grayscale image, I tried to modify the network input channel from three to one , but also failed.

**Comment by fracape** [comment]
Would need more details to debug this. Please follow the issue report template.

**Comment by Zhenxing-Dong** [comment]
I have changed the conv(3, N) to conv(1, N). But when I input a grayscale image, it still is conv(3, N).

It seems that my attempts to modify any function are futile.

**Comment by fracape** [comment]
> It seems that my attempts to modify any function are futile.

Then, as i said, it must be your environment. Please follow the template that comes with the bug report. Other users may help you if you provide the following: 

Please copy and paste the output from `python3 -m torch.utils.collect_env`

```
- PyTorch / CompressAI Version (e.g., 1.0 / 0.4.0):
- OS (e.g., Linux):
- How you installed PyTorch / CompressAI (`pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:
```
