### ISSUE TITLE
Downloading scale space flow model stuck at 0%

### ISSUE THREAD

**Issue by CarlosGomes98** [InterDigitalInc/CompressAI#218]
## Bug

When using the script codec.py from examples, the required model for the compression cannot be downloaded

## To Reproduce

1. run e.g. `python codec.py encode path_to_sample_video --cuda -q 6 --model ssf2020 -o test_bosphorus -f -1`

The download is stuck at 0

## Expected behavior
The model should download from https://compressai.s3.amazonaws.com/models/v1/ssf2020-mse-6-59dfb6f9.pth.tar". This does not work on a browser either, so I believe it might be an aws issue.

## Environment

Not relevant.

**Comment by fracape** [comment]
Hi, 

It works from here, are you sure you don't have any connection problem or issue with aws?

**Comment by CarlosGomes98** [comment]
Huh, downloading from a mobile connection seems to make it work, looks like it is something with my other connection. Super strange, sorry for the trouble
