### ISSUE TITLE
The default batch size is 10 times the input batch size

### ISSUE THREAD

**Issue by battlepeace** [InterDigitalInc/CompressAI#219]
Thank you for your work. I found the default batch size is 10 times the input batch size.
Is this your setting, and what's the point of doing so? Where can I find it?

**Comment by YodaEmbedding** [comment]
What are you referring to by the "default batch size" and "input batch size"?

The `examples/train.py` specifies a training batch size of 16:

https://github.com/InterDigitalInc/CompressAI/blob/ee91d536bd934fc1f8b1532f78db4c94072ae26d/examples/train.py#L198-L200

The [documentation](https://interdigitalinc.github.io/CompressAI/zoo.html#training) states:

> Models were trained with a batch size of 16 or 32

**Comment by battlepeace** [comment]
I mean, when I'm training, the batch size I specify is 16, but when I print out a file, it's 160 times. Is this your setting?
![image](https://user-images.githubusercontent.com/49899631/226091864-e9e9f5ce-b395-4afe-b0c9-45cd6409620a.png)

**Comment by YodaEmbedding** [comment]
That's probably just the default interval for printing the progress bar.

https://github.com/tqdm/tqdm#documentation

The actual batch size is still 16, which you can check by printing out `x.shape`.

**Comment by battlepeace** [comment]
Thank you very much for your answer. I wish you a happy life and work
