### ISSUE TITLE
Microsoft Visual C++ error while installing CompressAI package and  "compressai._CXX" modules

### ISSUE THREAD

**Issue by Reza-MohammadiAsiyabi** [InterDigitalInc/CompressAI#220]
While installing the CompresAI package using pip, I receive "ERROR: Command errored out with exit status 1:" and "error: Microsoft Visual C++ 14.0 or greater is required.".
As a result I cannot import the "compressai._CXX" modules.

Below is the full log of the installation:

(D3net) D:\Reza\My Python Projects\New Project\compressai>pip install -U pip && pip install -e .
Requirement already satisfied: pip in c:\programdata\anaconda3\envs\d3net\lib\site-packages (21.3.1)
Obtaining file:///D:/Reza/My%20Python%20Projects/New%20Project/compressai
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\programdata\anaconda3\envs\d3net\lib\site-packages (from compressai==1.2.4.dev0)  (1.19.5)
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\envs\d3net\lib\site-packages (from compressai==1.2.4.dev0) (3.3.4)
Requirement already satisfied: torchvision in c:\programdata\anaconda3\envs\d3net\lib\site-packages (from compressai==1.2.4.dev0) (0.11.3)
Requirement already satisfied: pytorch-msssim in c:\programdata\anaconda3\envs\d3net\lib\site-packages (from compressai==1.2.4.dev0) (0.2.1)
Requirement already satisfied: torch>=1.7.1 in c:\programdata\anaconda3\envs\d3net\lib\site-packages (from compressai==1.2.4.dev0) (1.10.2)
Requirement already satisfied: scipy in c:\programdata\anaconda3\envs\d3net\lib\site-packages (from compressai==1.2.4.dev0) (1.5.3)
Requirement already satisfied: typing_extensions in c:\programdata\anaconda3\envs\d3net\lib\site-packages (from torch>=1.7.1->compressai==1.2.4.dev0) (4.1.1)
Requirement already satisfied: dataclasses in c:\programdata\anaconda3\envs\d3net\lib\site-packages (from torch>=1.7.1-compressai==1.2.4.dev0) (0.8)
Requirement already satisfied: pillow>=6.2.0 in c:\programdata\anaconda3\envs\d3net\lib\site-packages (from matplotlib-compressai==1.2.4.dev0) (8.3.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\programdata\anaconda3\envs\d3net\lib\site-packages (from matplotlib->compressai==1.2.4.dev0) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in c:\programdata\anaconda3\envs\d3net\lib\site-packages (from matplotlib->compressai==1.2.4.dev0) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\envs\d3net\lib\site-packages (from matplotlib-compressai==1.2.4.dev0) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\envs\d3net\lib\site-packages (from matplotlib->compressai==1.2.4.dev0) (1.3.1)
Requirement already satisfied: six in c:\programdata\anaconda3\envs\d3net\lib\site-packages (from cycler>=0.10->matplotlib->compressai==1.2.4.dev0) (1.16.0)
Installing collected packages: compressai
  Running setup.py develop for compressai
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\D3net\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\Reza\\My Python Projects\\New Project\\compressai\\setup.py'"'"'; __file__='"'"'D:\\Reza\\My Python Projects\\New
Project\\compressai\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else i o.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close()
;exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: D:\Reza\My Python Projects\New Project\compressai\
    Complete output (17 lines):
    running develop
    running egg_info
    writing compressai.egg-info\PKG-INFO
    writing dependency_links to compressai.egg-info\dependency_links.txt
    writing requirements to compressai.egg-info\requires.txt
    writing top-level names to compressai.egg-info\top_level.txt
    reading manifest file 'compressai.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    writing manifest file 'compressai.egg-info\SOURCES.txt'
    running build_ext
    building 'compressai.ans' extension
    C:\Users\CEOSpace\AppData\Local\Temp\pip-build-env-sr_bare3\overlay\Lib\site-packages\setuptools\command\easy_install.p
y:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    C:\Users\CEOSpace\AppData\Local\Temp\pip-build-env-sr_bare3\overlay\Lib\site-packages\setuptools\command\install.py:37:
 SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.
microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\envs\D3net\python.exe' -c 'import io, os, sys, set
uptools, tokenize; sys.argv[0] = '"'"'D:\\Reza\\My Python Projects\\New Project\\compressai\\setup.py'"'"'; __file__='"'"'D:\\Reza\\My Python Projects\\New Project\\compressai\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

I have installed the Microsoft Visual C++ from the "Microsoft C++ Build Tools" as it is described in the error log but I still have the same problem.
I would appreciate it if you can help me solve this.

**Comment by fracape** [comment]
Hi, 
We don't develop and test on windows, but I recently installed from source (pip install path/to/compressai) on a windows machine (with vs build tools since we have cpp extensions) and it worked fine (no anaconda).

**Comment by Reza-MohammadiAsiyabi** [comment]
Thank you @fracape for the reply. I resolved the problem by updating the VS build tools.
