### ISSUE TITLE
How to visualize the bitstream compressed by the entropybottleneck

### ISSUE THREAD

**Issue by tuning12** [InterDigitalInc/CompressAI#234]
Firstly thank you for your work !

I would like to visualize the bitstream produced by the function 'entropy_bottleneck.compress()' and it returns a list of bytes. What should I do if I want to check the bitstream? I tried to add this 'self.bottleneck.compress(y)[0].decode()' but it failed and returns 'UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8f in position 2: invalid start byte'.

**Comment by YodaEmbedding** [comment]
What do you mean by visualizing the bitstream? If the entropy model is decent, every bit of the resulting bitstream should be i.i.d. and effectively be drawn from a uniform distribution.

Perhaps you want to visualize a specific realization y of the vector random variable Y instead?

**Comment by YodaEmbedding** [comment]
To get the bitstreams:

```python
from compressai.zoo import mbt2018
from PIL import Image
from torchvision import transforms

device = "cuda"
net = mbt2018(quality=2, pretrained=True).eval().to(device)
img = Image.open("/data/datasets/kodak/test/kodim01.png").convert("RGB")
x = transforms.ToTensor()(img).unsqueeze(0).to(device)

with torch.no_grad():
    out_enc = net.compress(x)

[y_strings, z_strings] = out_enc["strings"]
print(y_strings[0])
print(z_strings[0])
```

**Comment by tuning12** [comment]
Thank you for your patient reply. it is a good solution! Have a nice day
