### ISSUE TITLE
Where the functions are？

### ISSUE THREAD

**Issue by RizerKayseri** [InterDigitalInc/CompressAI#251]
When i read the program written by others, some errors have occurred.

I cannot reference the following functions
from compressai.ops import **ste_round** as ste_round
from compressai.**ans** import BufferedRansEncoder, RansDecoder

**Comment by ayuzy** [comment]
I have encountered the same problem, may I ask how this is solved

**Comment by RizerKayseri** [comment]
> Change the line giving the `ImportError` to:
> 
> ```python
> import compressai.ops.ops.quantize_ste as ste_round
> ```

thank you very much

**Comment by RizerKayseri** [comment]
> I have encountered the same problem, may I ask how this is solved

It is difficult to recall my method at that time; I suggest that you review another response.
https://github.com/InterDigitalInc/CompressAI/issues/251#issuecomment-1958896803

**Comment by dylan-d-hub** [comment]
from compressai.ops import quantize_ste as ste_round
