### ISSUE TITLE
Is it allowed to update the EntropyBottleneck while training?

### ISSUE THREAD

**Issue by tuning12** [InterDigitalInc/CompressAI#253]
Thanks for your excellent work. I wonder if it is allowed to update the EntropyBottleneck while training. I still couldn't understand what "update" are doing.

**Comment by YodaEmbedding** [comment]
`update` fills in the discretized CDFs. Those are not used during training. They are used during `compress` and `decompress`. Just be sure to call `update(force=True)` immediately before each test/infer epoch, e.g., https://github.com/InterDigitalInc/CompressAI-Trainer/blob/master/compressai_trainer/runners/base.py#L90-L92

**Comment by tuning12** [comment]
Thank you for your reply.
