### ISSUE TITLE
Inconsistency between training and testing procedures

### ISSUE THREAD

**Issue by mosquitobite** [InterDigitalInc/CompressAI#3]
Thanks for your work! I notice there seems to have inconsistency between training and testing procedures, regarding entropy coding of latent representation y and hyperprior z.
 
During training, quantized [y] (which is simulated by using additive Gaussian noise) is coded. Yet during testing, quantized [y - means_hat] is coded. And the same for hyperprior z.

My question is why training and testing procedures are different? Is there any special consideration for this? And will this influence coding performance?

**Comment by jbegaint** [comment]
Hi, thanks for trying out CompressAI!

Additive "uniform" noise (not Gaussian noise) is used during training to make the bottlenecks differentiable.

When testing, the rounding operations are only applied to the "centered" latent values (y-means_hat for example), this is more efficient compression wise when using range coding to work on centered distributions. During training, adding quantization noise to the latent or the "centered" latent is equivalent.
