### ISSUE TITLE
argparse does not like metavar as empty strings

### ISSUE THREAD

**Issue by navid-mahmoudian** [InterDigitalInc/CompressAI#31]
Hello,

When I use `python3 -m compressai.utils.bench vtm --help` I get the following error:

> File "/usr/lib/python3.8/argparse.py", line 349, in _format_usage
>     assert ' '.join(opt_parts) == opt_usage
> AssertionError

When I searched on net I found this [link](https://stackoverflow.com/questions/28678739/assertion-when-declaring-required-arguments-with-argparse-and-nargs-argument/28679089) that explains

> argparse does not like metavar=''.
> 
> Either give them a name or remove the options - but don't leave them as empty strings.
> 

When I comment the `metavar=''` in `compressai/utils/bench/codecs.py`, then the program works properly. The same problem exists for `hm` as well.

Thank you very much again for this nice package.

**Comment by jbegaint** [comment]
Hi Navid, thanks again for your reports :-). We'll fix that soon.

**Comment by navid-mahmoudian** [comment]
Hi Jean,

Thank you for your support. I have another question. For reproducibility, could you please tell me which **config file** you have used in your experiments reported in your arXiv paper (CompressAI: a PyTorch library and evaluation platform for end-to-end compression research) for VTM? Also, the one you presented is with **RGB mode** or **YCbCr mode**?

**Comment by jbegaint** [comment]
pretty sure i used the `encoder_intra_vtm.cfg` from VTM 7.1 or 9.1 at the time. YCbCr mode by default + the extra parameters in `codecs.py` from compressai.

**Comment by jbegaint** [comment]
Fixed in master.
