### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by OzanKara41** [InterDigitalInc/CompressAI#32]
I trained(In examples/train.py) a model with my own dataset. But i don't know how to evaluate with toy model, can u help me ? If it is not possible, how can i do that with my own dataset using bmshj2018-factorized architecture ? I should use my own dataset.  Thank you.

**Comment by jbegaint** [comment]
Hi @OzanKara41, I've just updated the example training script to allow training of the predefined model.
You should be able to train the `bmshj2018-factorized` architecture now.

**Comment by OzanKara41** [comment]
I'll use this code again, right?  
`python3 examples/train.py -d /path/to/my/image/dataset/ --epochs 300 -lr 1e-4 --batch-size 16 --cuda --save`
After the train, a checkpoint will be created than i'll use this evalutation code below
`python3 -m compressai.utils.eval_model checkpoint /path/to/images/folder/ -a bmshj2018-factorized -p checkpoint.pth.tar`
Can u check it ? Thank you for quick reply.

**Comment by jbegaint** [comment]
yes that looks right!
