### ISSUE TITLE
About Pretrained models of Cheng2020Anchor at high bit rates

### ISSUE THREAD

**Issue by BYchao100** [InterDigitalInc/CompressAI#35]
The pretrained models of Cheng2020Anchor do not cover bit rates higher than 1 bpp (only 1-6 models). I try to train Cheng2020Anchor at high bit rates by increasing lambda or number of channels, but find the performance degrades severely compared with other methods. Do the developers find the same problem? Is it possible to include Cheng2020Anchor at higher bit rates (>1bpp) like other methods in the pretrained model? 

I appreciate if the developers can give me some advice.

**Comment by jbegaint** [comment]
Hi, we provided the 6 sets of pretrained weights to reproduce the results presented in this bit-rate range in the original paper.

If you increase both the lambda and the number of channels it should be able to handle larger bit-rates, the base architecture is very similar to other publications. Can you try the a larger lambda [1] and use 192 output channels for the intermediate feature maps and 320 for the latent ? 

[1]: https://interdigitalinc.github.io/CompressAI/zoo.html#training

**Comment by BYchao100** [comment]
Thank you for your reply! I tried exactly what you recommend but the performance was quite different from what I expected. I modified the Cheng2020Anchor class in order to adjust the latent. By using (N=192, M=320) and lambda 1, the converged performance of Cheng2020Anchor on Kodak is bpp: 2.34, psnr:40.98. For mbt2018, I use (N=192, M=320), lambda 0.5, the converged performance on Kodak is bpp: 2.39, psnr: 42.99. 

By using (N=192, M=192), lambda 0.025,  the converged performance of Cheng2020Anchor on Kodak is bpp: 0.59, psnr:35.11, which is consistent with the original paper.

I don't know if I make mistakes or Cheng2020Anchor is not suitable for high bit-rates. Thus, I wonder if you met the same problem.

The modified class:
class Cheng2020Anchor(JointAutoregressiveHierarchicalPriors):

    def __init__(self, N=192, M=192, **kwargs):
        super().__init__(N=N, M=M, **kwargs)

        self.g_a = nn.Sequential(
            ResidualBlockWithStride(3, N, stride=2),
            ResidualBlock(N, N),
            ResidualBlockWithStride(N, N, stride=2),
            ResidualBlock(N, N),
            ResidualBlockWithStride(N, N, stride=2),
            ResidualBlock(N, M),
            conv3x3(M, M, stride=2),
        )

        self.h_a = nn.Sequential(
            conv3x3(M, N),
            nn.LeakyReLU(inplace=True),
            conv3x3(N, N),
            nn.LeakyReLU(inplace=True),
            conv3x3(N, N, stride=2),
            nn.LeakyReLU(inplace=True),
            conv3x3(N, N),
            nn.LeakyReLU(inplace=True),
            conv3x3(N, N, stride=2),
        )

        self.h_s = nn.Sequential(
            conv3x3(N, M),
            nn.LeakyReLU(inplace=True),
            subpel_conv3x3(M, M, 2),
            nn.LeakyReLU(inplace=True),
            conv3x3(M, M * 3 // 2),
            nn.LeakyReLU(inplace=True),
            subpel_conv3x3(M * 3 // 2, M * 3 // 2, 2),
            nn.LeakyReLU(inplace=True),
            conv3x3(M * 3 // 2, M * 2),
        )

        self.g_s = nn.Sequential(
            ResidualBlock(M, N),
            ResidualBlockUpsample(N, N, 2),
            ResidualBlock(N, N),
            ResidualBlockUpsample(N, N, 2),
            ResidualBlock(N, N),
            ResidualBlockUpsample(N, N, 2),
            ResidualBlock(N, N),
            subpel_conv3x3(N, 3, 2),
        )

**Comment by BYchao100** [comment]
Thank you for your patient reply! Let me try different learning rates and train longer time.

**Comment by jbegaint** [comment]
Closing stale issue. If you think it should remain open, feel free to reopen it.
