### ISSUE TITLE
Zoo models crash at large image size.

### ISSUE THREAD

**Issue by ifeherva** [InterDigitalInc/CompressAI#36]
I have a dataset of image if 1280x720 and it seems the zoo models cannot compress these, I get all kinds of errors related to mismatching tensor sizes. Is this expected due to image size or a bug?

**Comment by jbegaint** [comment]
you need to pad the image (because of the stride convolution/deconvolution), see an example here: https://github.com/InterDigitalInc/CompressAI/blob/master/examples/codec.py#L162

**Comment by ifeherva** [comment]
Thank you, this really helps. This is an awesome repo!
