### ISSUE TITLE
Encoding/Decoding time

### ISSUE THREAD

**Issue by PascalBACCHUS** [InterDigitalInc/CompressAI#45]
Hello Jean,

I evaluate the pretrained models on any datasets I found different encoding/decoding time depending on the quality of the reconstruction for the same model. Is this to be expected? I thought the time would be the same if the network does not change.
Maybe it's just jobs in my background that may slow down things during runtime but it is consistent every time. Higher quality always gives a slightly higher running time.

Thank you.

**Comment by jbegaint** [comment]
Hi Pascal, yes the higher quality networks have more channels (https://github.com/InterDigitalInc/CompressAI/blob/master/compressai/zoo/image.py#L131). The networks need more channels at high bit-rates to get the best performances.

**Comment by PascalBACCHUS** [comment]
I completely overlook that part of the architecture. I thought the "quality" parameter was defining both the lambda and architecture parameter.
Thank you.
