### ISSUE TITLE
A small question about updating entropybottleneck

### ISSUE THREAD

**Issue by Cyprus-hy** [InterDigitalInc/CompressAI#50]
Hi, I really appreciate for your work, but I have a small question about updating entropybottleneck. That is, I insert a entropybottleneck in my network, and I save it after training without calling updata. When I do inference, I load checkpoint first and then call the update function of entropybottleneck, should this work ok？ Or I should update entropybottleneck before save, and load checkpoint without update when I do inference. Thanks a lot.

**Comment by jbegaint** [comment]
Hi, you can do both, but I'd recommend running update only once and then saving the checkpoint. You can use `compressai.utils.update_model` for this purpose if you use one of the implemented models.

**Comment by Cyprus-hy** [comment]
Thanks for your reply. I find that when I use "CompressionModel" to organize my network, the two ways(update->save->load and save->load->update) are both work ok. But if I use "nn.Module" instead, only save->load->update works, the other way reports a error, which seems like the size of parameters(the three in the update function) mismatch, which makes me confused. After I see the source code, I realize that you rewrite the "load_state_dict" function of CompressionModel, in which you change the size of parameters. So I guess maybe that's the reason, and in fact both the two ways are correct, because the buffers are also be loaded when we call "torch.load".

**Comment by Cyprus-hy** [comment]
> Hi, you can do both, but I'd recommend running update only once and then saving the checkpoint. You can use `compressai.utils.update_model` for this purpose if you use one of the implemented models.

Thanks for your reply. I find that when I use "CompressionModel" to organize my network, the two ways(update->save->load and save->load->update) are both work ok. But if I use "nn.Module" instead, only save->load->update works, the other way reports a error, which seems like the size of parameters(the three in the update function) mismatch, which makes me confused. After I see the source code, I realize that you rewrite the "load_state_dict" function of CompressionModel, in which you change the size of parameters. So I guess maybe that's the reason, and in fact both the two ways are correct, because the buffers are also be loaded when we call "torch.load".

**Comment by jbegaint** [comment]
Yes, we need to resize the internal buffers related to the CDFs static parameters when loading a model. For most cases, inheriting from one of the predefined architectures should be enough.

**Comment by jbegaint** [comment]
Please re-open if you encounter any issues.

**Comment by Cyprus-hy** [comment]
I am sorry to bother you again, but I have a question about bpp calculation. I construct a toy network, which try to compress a float data that is randomly generated. After training, I do a inference also on the train data. What makes me confused is that the actual bpp(calculated by the length of compressed string) is almost twice as larger as the theoretical bpp(calculated by likelihoods). But shouldn't the actual bpp be almost the same as the theoretical bpp? Hope for your reply, thanks a lot.
The following is code:
```python
from compressai.models import CompressionModel
import torch
from torch.nn import Linear,MaxPool1d
import torch.nn as nn
import torch.optim as optim
from torch.nn import MSELoss
import math

# redefine maxpool
def maxpool(x, dim=-1):
    out, _ = x.max(dim=dim)
    return out

class Network(CompressionModel):
    def __init__(self, N=3):
        super().__init__(entropy_bottleneck_channels=32)
        self.encode = nn.Sequential(
            Linear(N, 64),
            Linear(64,128),
            Linear(128, 32)
        )

        self.decoder = nn.Sequential(
            Linear(32, 32*3),
            Linear(32*3, 64*N)
        )
        self.pool = maxpool

    def forward(self,x):
        b = x.shape[0]
        x = self.encode(x)
        latent_code = self.pool(x, dim=1)
        y_hat, y_likelihoods = self.entropy_bottleneck(latent_code)
        x_hat = self.decoder(y_hat)
        x_hat = x_hat.reshape(b, -1 ,3)

        return x_hat, y_likelihoods

# loss
loss = MSELoss()

# Data
torch.manual_seed(10)
data = torch.rand(10,64,3).float().cuda()
#
# Model
model = Network().cuda()
# optimizer
parameters = set(p for n, p in model.named_parameters() if not n.endswith(".quantiles"))
aux_parameters = set(p for n, p in model.named_parameters() if n.endswith(".quantiles"))
optimizer = optim.Adam(parameters, lr=1e-4)
aux_optimizer = optim.Adam(aux_parameters, lr=1e-3)

# train
for i in range(10000):
    optimizer.zero_grad()
    aux_optimizer.zero_grad()

    x_hat, y_likelihoods = model(data)

    mse_loss = loss(x_hat, data)
    B,N, H = data.size()
    num_pixels = B * N
    bpp_loss = torch.log(y_likelihoods).sum() / (-math.log(2) * num_pixels)
    distortion_loss = mse_loss + 1e-2 * bpp_loss
    distortion_loss.backward()
    optimizer.step()

    aux_loss = model.aux_loss()
    aux_loss.backward()
    aux_optimizer.step()

    # if (i+1) %1000 == 0:
    #     print("iteration:", i+1)
    #     print("distortion loss:", distortion_loss)
    #     print('bpp_loss:',bpp_loss.item())
    #     print('mse_loss:',mse_loss.item())
    #     print('aux_loss:',aux_loss.item())

torch.save(model.state_dict(),'./model2.pth')

# # load
model2 = Network().cuda()
ckpt = torch.load('./model2.pth')
model2.load_state_dict(ckpt)
model2.update()

_, y_likelihoods = model2.forward(data)
# print(model2.aux_loss())
print('theoretical bpp:', (torch.log(y_likelihoods).sum() / (-math.log(2) * 10 * 64)).item())

x = model2.encode(data)
y = model2.pool(x, dim=1)
string = model2.entropy_bottleneck.compress(y)
bpp = sum(len(s) for s in string) * 8.0 / (10*64)
print('actual bpp:', bpp)
y_hat = model2.entropy_bottleneck.decompress(string, [])
x_hat = model2.decoder(y_hat)
x_hat = x_hat.reshape(10,-1,3)
```
