### ISSUE TITLE
Error:: Model Update and Model Evaluation

### ISSUE THREAD

**Issue by Biaze7** [InterDigitalInc/CompressAI#55]
First of all, thank you for the awesome work :D

After training, I'm trying to run `compressai.utils.update_model` on my training checkpoint.

So, I used:
```
python -m compressai.utils.update_model -h
```

And:
```
python -m compressai.utils.update_model /content/checkpoint_best_loss.pth.tar
```
(Should I use checkpoint_best_loss.pth.tar or checkpoint_pth.tar??)

It returned the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/compressai/utils/update_model/__main__.py", line 139, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.7/dist-packages/compressai/utils/update_model/__main__.py", line 110, in main
    net = model_cls.from_state_dict(state_dict)
  File "/usr/local/lib/python3.7/dist-packages/compressai/models/priors.py", line 277, in from_state_dict
    net.load_state_dict(state_dict)
  File "/usr/local/lib/python3.7/dist-packages/compressai/models/priors.py", line 267, in load_state_dict
    state_dict,
  File "/usr/local/lib/python3.7/dist-packages/compressai/models/utils.py", line 108, in update_registered_buffers
    dtype,
  File "/usr/local/lib/python3.7/dist-packages/compressai/models/utils.py", line 54, in _update_registered_buffer
    new_size = state_dict[state_dict_key].size()
KeyError: 'gaussian_conditional._quantized_cdf'
```

What's wrong?

-------------------------------------------------------------------------------------
After this I can run the evaluation, right?
But which positional argument, should I use? Pretrained or Checkpoint?

Running this:
```python -m compressai.utils.eval_model -h

usage: __main__.py [-h] {pretrained,checkpoint} ...

Evaluate a model on an image dataset.

positional arguments:
  {pretrained,checkpoint}
                        model source

optional arguments:
  -h, --help            show this help message and exit
```

Could you help me with these two topics, please?
Thank you.

**Comment by jbegaint** [comment]
Hi,

- Can you provide a bit more information on your setup?
  * Can you run `python3 -m torch.utils.collect_env` 
  * report the `compressai` package version
  * which model are you training?
- The `*_best_loss.pth.ar` is a copy of the checkpoint with the minimum loss achieved with the example training script ([see here](https://github.com/InterDigitalInc/CompressAI/blob/master/examples/train.py#L338)).
- since you are using your own trained model, you should use the `checkpoint` argument in the evaluation script.

**Comment by Biaze7** [comment]
Hi Jean, thank you for answering.

1) When I ran: python3 -m torch.utils.collect_env, I got:

Collecting environment information...
PyTorch version: 1.8.1+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-msssim==0.2.1
[pip3] torch==1.8.1+cu101
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.9.1
[pip3] torchvision==0.9.1+cu101
[conda] Could not collect


I guess that it is important say I was using colab to do some tests, but this week, I'm gonna use a computer with GPU and conda environment.

2) The compressai package version is 1.1.5.
3) I'm using bmshj2018-factorized, with my selected images.
Thank you.

**Comment by jbegaint** [comment]
you need to pass the correct architecture to `compressai.utils.update_model`, otherwise `torch.load` will fail.
