### ISSUE TITLE
A question about using jpeg2000

### ISSUE THREAD

**Issue by YocurryC** [InterDigitalInc/CompressAI#58]
Hello, I'm sorry to bother you, I have a question when I use this project about jpeg2000.  Should I download ffmpeg and openjpeg by myself? Thanks.

**Comment by fracape** [comment]
Yes, we used ffmpeg's implementation of jpeg2000 for our comparisons. You need to install it to use [the evaluation scripts](https://github.com/InterDigitalInc/CompressAI/blob/caf4aa79e39beed1fc974bb456dd8aa1009c3e3a/compressai/utils/bench/codecs.py#L274) on your dataset.

**Comment by YocurryC** [comment]
Thanks for your answer! But just installing ffmpeg didn't work either. Does this project also need the OpenJPEG library compiled by C language? Or is my FFmpeg installation  in the wrong directory?  Sorry to bother you.

**Comment by fracape** [comment]
Please refer to https://ffmpeg.org/ffmpeg-codecs.html#jpeg2000 for ffmpeg

**Comment by xuezhongcailian** [comment]
Hello, what are the versions of FFMpeg and JPEG2000. And the size of different pictures at the same compression level is the same

**Comment by YI-MAX-YAN** [comment]
Hello, I am also unable to run JPEG2000. If it's convenient for you, could you please let me know which libraries I need to download? This would be a great help to me.
