### ISSUE TITLE
Quantization in `JointAutoregressiveHierarchicalPriors`

### ISSUE THREAD

**Issue by fujibo** [InterDigitalInc/CompressAI#6]
Thank you for your great work.

I noticed that `torch.round` is directly used in the implementation of `JointAutoregressiveHierarchicalPriors`.
https://github.com/InterDigitalInc/CompressAI/blob/master/compressai/models/priors.py#L549
I think the quantization should be performed using `self.gaussian_conditional` like other classes extended from `CompressionModel`. More specifically, `self.gaussian_conditional._quantize` should be used.

This implementation is consistent with that for dequantization.
https://github.com/InterDigitalInc/CompressAI/blob/master/compressai/models/priors.py#L637

**Comment by jbegaint** [comment]
hey, thanks for the comment! 

It's equivalent in this case but you are right that it would be more consistent to use `_quantize`. I'll update this, thanks!
