### ISSUE TITLE
About get_scale_table(min=SCALES_MIN, max=SCALES_MAX, levels=SCALES_LEVELS)

### ISSUE THREAD

**Issue by Junx0924** [InterDigitalInc/CompressAI#64]
## Documentation

The original default values are:
#https://github.com/InterDigitalInc/CompressAI/blob/release/1.1.1/compressai/models/priors.py

SCALES_MIN = 0.11
SCALES_MAX = 256
SCALES_LEVELS = 64

When the input image data is 16 bit instead of 8 bit, should these values be changed according to the data range? and how to decide the SCALES_LEVELS with new data range?

**Comment by jbegaint** [comment]
Probably not. Though you can check easily by (1) passing your own `scale_table` to the `update` function [here](https://github.com/InterDigitalInc/CompressAI/blob/976e05234b249678576bdc7909431598f518ee05/compressai/models/priors.py#L280) and (2) evaluating the model performances on some images.

**Comment by YuKDseele** [comment]
Hi, I wanted to ask if you have resolved this problem, as I am now encountering a similar problem. I am using 12-bit images and unsure whether I need to modify SCALES_MAX and SCALES_LEVELS. However, from the results, it seems that compression can still work, although the results may not be ideal.
