### ISSUE TITLE
Doubts about command lines

### ISSUE THREAD

**Issue by KimWooah** [InterDigitalInc/CompressAI#66]
Hello, first, thank you for sharing the good work.

I'm trying to use the plot command, to know the repository, described at: https://interdigitalinc.github.io/CompressAI/cli_usage.html

Please, what should I put on -f ? I didn't understand.
What is this: -f [ [ ...]], --results-file [ [ ...]] ?

Other thing is: after update the model with my own trained model, for example, will I be able to run the command:
python3 examples/codec.py with an own image ?

Thanks.

**Comment by jbegaint** [comment]
Hi @KimWooah ,

The _result files_ are generated by evaluating the models with [`compressai.tools.eval_model`](https://interdigitalinc.github.io/CompressAI/cli_usage.html#eval-model) or the `compressai.utils.bench` utility.

The `examples/codec.py` uses the pre-defined architectures with pre-trained weights but you should be able to extend it to load your own model/weights.
