### ISSUE TITLE
Context model

### ISSUE THREAD

**Issue by nedahei** [InterDigitalInc/CompressAI#67]
Dear authors,

I have a question concerning context model. I am trying to train my customized model without pretrained model . I could hopefully train the model. But during the inference, I don't know where to put the context model in the architecture?!

**Comment by jbegaint** [comment]
Hi, I'm not sure I understand, are you referring to the context in the Minnen et al. [architecture](https://github.com/InterDigitalInc/CompressAI/blob/master/compressai/models/priors.py#L380)? Could you share a small example of what you are training to do?

**Comment by jbegaint** [comment]
Closing stale issue. If you think it should remain open, feel free to reopen it.
