### ISSUE TITLE
Why num_pixels is calculated by batchsize*img_width*img_height without img_channels

### ISSUE THREAD

**Issue by Junx0924** [InterDigitalInc/CompressAI#70]
I know this question may sound very stupid, but I checked the codes and really can't figure out know why.
In https://github.com/InterDigitalInc/CompressAI/blob/master/examples/train.py:
```
class RateDistortionLoss(nn.Module):
    """Custom rate distortion loss with a Lagrangian parameter."""
    def __init__(self, lmbda=1e-2):
        super().__init__()
        self.mse = nn.MSELoss()
        self.lmbda = lmbda
   def forward(self, output, target):
        N, _, H, W = target.size()
        out = {}
        num_pixels = N * H * W
        out["bpp_loss"] = sum(
            (torch.log(likelihoods).sum() / (-math.log(2) * num_pixels))
            for likelihoods in output["likelihoods"].values()
        )
```

The input images are RGB images, can I ask why the image channels were not counted when calculating **num_pixels**?

**Comment by fracape** [comment]
Hi Junx0924, a pixel is an element (location) of the picture. If the image is RGB, the pixel has a triplet of values.

**Comment by Junx0924** [comment]
Hi Fabien, thanks a lot, I understand it now. Silly me.

**Comment by fracape** [comment]
No problem
