### ISSUE TITLE
metric NAN output when evaluating a model

### ISSUE THREAD

**Issue by ZhangYuef** [InterDigitalInc/CompressAI#71]
## Bug

I got NAN output on PSNR and MS-SSIM when evaluating this example image `examples/assets/stmalo_fracape.png`  but both metrics went correct when evaluating on kodak dataset.

## To Reproduce

1. Train `Cheng2020Anchor`
2. Update entropy parameters
3. Evaluate

It's a similar problem as issue #54 , but we already have `torch.backends.cudnn.deterministic = True` in evaluation file `compressai/utils/eval_model/__main__.py`.

## Environment

```
- PyTorch / CompressAI Version (e.g., 1.0 / 0.4.0): 1.8 / 1.15
- OS : linux
- Python version: 3.6
```

**Comment by guoguo1314** [comment]
Brother, did you solve the problem? I also met.I also add torch.backends.cudnn.deterministic = True in evaluation

**Comment by bblgbr** [comment]
Hi, did you solve the problem? I also met.I also add torch.backends.cudnn.deterministic = True in evaluation
