### ISSUE TITLE
JIT not working for (de)compress

### ISSUE THREAD

**Issue by YannDubs** [InterDigitalInc/CompressAI#72]
## Bug

I see that you are testing whether JIT of the EntropyBottleneck works (and it does), but JITing the compress/decompress method of an entropy bottleneck does not work. which means that as a whole the ENtropy Bottleneck cannot really be used with JIT.

## To Reproduce

```python
from compressai.entropy_models import EntropyBottleneck
import torch

torch.jit.script(EntropyBottleneck(4).compress)
torch.jit.script(EntropyBottleneck(4).decompress)
```

![Screen Shot 2021-07-06 at 11 07 07](https://user-images.githubusercontent.com/24327668/124574125-7661d000-de4a-11eb-9d53-508bbffb7b58.png)
![Screen Shot 2021-07-06 at 11 10 46](https://user-images.githubusercontent.com/24327668/124574536-db1d2a80-de4a-11eb-98fb-6c9cac9756ce.png)

## Expected behavior

Successful JIT conversion.

## Environment

```
- compressai==1.1.5
- torch==1.7.1
```

**Comment by jbegaint** [comment]
hey, thanks for the report. I don't think there's anything we can do at this point to address this. The entropy modules compress/decompress methods rely on inheritance and dynamic lists which are not supported by torchscript. I'm not even sure we can export these methods anyway since we are also calling a c++ extension. Any reasons you want to use torchscript here?

**Comment by YannDubs** [comment]
I see.

Nothing crucial but I put a [new pretrained compressor](https://arxiv.org/abs/2106.10800) on [torchhub](https://pytorch.org/hub/), and they give the choice of downloading the model in a scripted version and mine wasn't working.

**Comment by jbegaint** [comment]
ah yes, that's an interesting use case. I'll keep this open for now until we figure out the next steps.

**Comment by fracape** [comment]
closing for now, accepting related PR
