### ISSUE TITLE
Using --half when evaluating a model

### ISSUE THREAD

**Issue by ShimaMohammadi** [InterDigitalInc/CompressAI#73]
## Bug

Hi. I have  problems using model evaluation. I used --half as argument to eval_model, But facing following error;
input type (torch.cuda.floattensor) and weight type (torch.cuda.halftensor) should be the same.

Training model has no issue but evaluation raised error of Cuda out of memorry

## To Reproduce

1. python3 examples/train.py -m mbt2018-mean -d /path/to/image/dataset \
    --batch-size 16 -lr 1e-4 --save --cuda
2. python -m compressai.utils.update_model --architecture ARCH checkpoint_best_loss.pth.tar

3. python -m compressai.utils.eval_model checkpoint /path/to/image/dataset \
    -a ARCH -p path/to/checkpoint-xxxxxxxx.pth.tar --half --verbose

## Environment

Please copy and paste the output from `python3 -m torch.utils.collect_env`

```
- PyTorch / CompressAI Version (e.g., 1.0 / 0.4.0):
- OS (e.g., Linux):
- How you installed PyTorch / CompressAI (`pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:
```

**Comment by fracape** [comment]
Hi. You mention 2 errors: halftensor and memory, can you copy/paste the actual error(s). Does it also happen if you evaluate a pre-trained model from compressai zoo directl? Can you show the output of torch.utils.collect_env? Did not seem to work (above). Thanks

**Comment by ShimaMohammadi** [comment]
Regarding halftensor: 
    This is the error: 
![Screenshot (5)](https://user-images.githubusercontent.com/38960586/125067756-e92cae80-e0c9-11eb-9d02-9d4e301f1e0d.png)
    - It is because y_hat in line 304 of priors.py is Floattensor.
    - It is happen on pretrained models as well.


Regarding memory:
    
![Screenshot (6)](https://user-images.githubusercontent.com/38960586/125069248-be435a00-e0cb-11eb-9230-2b54428ca3b6.png)
    -Evaluation throws out of memory in the second iteration, But training works fine. Even though torch.no_grad(): is used in 
        Evaluation.
    -Eval mode appears to use more memory than training mode, While theoretically it would just use the same. deleting 
       variables won't work.
     - It is happen on pretrained models as well.
   
![Screenshot (8)](https://user-images.githubusercontent.com/38960586/125072849-5e02e700-e0d0-11eb-8d67-d73c8195a31c.png)


Thanks

**Comment by fracape** [comment]
Hi, just got some time to look at this. I pushed a fix for the evaluation with half float. Please let me know how it goes with v1.1.6. As for memory, I would not agree that the usage is theoretically the same. For training, we usually crop patches of 256x256 to create batches, whereas at inference the whole images are processed. Depending on the resolution of you evaluation set, you might need more memory.
