### ISSUE TITLE
Use time.perf_counter() instead of time.time()

### ISSUE THREAD

**Issue by lbhm** [InterDigitalInc/CompressAI#77]
## Feature
Replace the `time.time()` calls in `utils.bench` (and possible other modules I'm not yet aware of) with `time.perf_counter()` or `time.perf_counter_ns()` (requires Python >= 3.7).

## Motivation
`time.time()` is not guaranteed to increase monotonically (https://docs.python.org/3/library/time.html#time.time). While this is usually not an issue, I have faced weird situations debugging this in other projects. Since the `utils.bench` module is only interested in the time difference and not the absolute time, using `time.perf_counter()` should not have any drawbacks.

**Comment by jbegaint** [comment]
Hey, thanks for the report. I don't really see the need to change something that's not broken. We can reconsider later if there are any actual bugs encountered.
