### ISSUE TITLE
Make codec-specific args available to the CLI

### ISSUE THREAD

**Issue by lbhm** [InterDigitalInc/CompressAI#78]
## Feature
~~The `Codec` class of the `utils.bench`module offers a method to define additional CLI arguments (`setup_args()`). However, with the current implementation of the surrounding methods (e.g., `_run()`, `run()` or `__main__.py`), it is not possible to use these arguments.~~

**Edit:** My original understanding of the `Codec` class was a bit shortsighted as I've overlooked `_set_args()`. Nevertheless, my motivation below that I would like to control `return_metrics` via the CLI still stands. As I understand it, every subclass of `Codec` uses these arguments in its `_run()` method so the two arguments could simply be added to `setup_common_args()'  in `__main__.py`.

## Motivation
I would like to be able to control the `return_metrics` parameter of `codec._run()` via the CLI. The reason is that I have a dataset with some images smaller than 160 pixels on which `pytorch-msssim` is throwing an error. I am mostly interested in benchmarking the encoding/decoding time so excluding the additional metrics would be fine for me.

**Comment by jbegaint** [comment]
Hey, thanks for the report. Just to make sure, you want to be able to manually select (or disable) the metrics computed right?

**Comment by lbhm** [comment]
Being able to select/disable each metric would be the ideal case I guess. For starters (and what I did in my local fork), it would help to simply make `return_metrics` controllable via the CLI to prevent `pytorch-msssim` throwing an error for small images.

**Comment by jbegaint** [comment]
thanks for the idea. We'll push some changes soon related to this issue.
