### ISSUE TITLE
Did the cheng2020_anchor and cheng2020_attn use the GMM(Gaussian mixture model)?

### ISSUE THREAD

**Issue by zhaiyongqi** [InterDigitalInc/CompressAI#79]
Hi, In Cheng's paper, **GMM(Gaussian Mixture Model)** was used as entropy model, but I did not find the code part of **GMM** in _compressai_. It seems like  _cheng2020_anchor_ and  _cheng2020_attn_ use the _JointAutoregressiveHierarchicalPriors_(**singel gaussian model**)? Looking forward to your reply! Thanks!

**Comment by jbegaint** [comment]
Hi, not at this point, no. We'll gladly accept a PR if you have an implementation and some results.
