### ISSUE TITLE
Question about HyperDecoder Architecture

### ISSUE THREAD

**Issue by soon0698** [InterDigitalInc/CompressAI#80]
![image](https://user-images.githubusercontent.com/31674784/127851775-c9dce338-0054-4bde-b9f5-51b2351e8613.png)
*Joint Autoregressive and Hierarchical Priors for Learned Image Compression

I just noticed that HyperDecoder ```(h_s)``` of ```JointAutoregressiveHierarchicalPriors``` is different from the paper.

```        
self.h_s = nn.Sequential(
            deconv(N, M, stride=2, kernel_size=5),
            nn.LeakyReLU(inplace=True),
            deconv(M, M * 3 // 2, stride=2, kernel_size=5),
            nn.LeakyReLU(inplace=True),
            **conv(M * 3 // 2, M * 2, stride=1, kernel_size=3)**
        )
```

Is there a reason for this? Am I something missing?

**Comment by jbegaint** [comment]
Sorry, but which difference exactly are you referring to?

**Comment by soon0698** [comment]
The HyperDecoder is consisted of 3 deconv layer, but ```h_s``` in code is consisted of 2 deconv layer and 1 conv layer.

**Comment by jbegaint** [comment]
but the last stride is 1, so the difference should not have any impact on performances.

**Comment by soon0698** [comment]
I thought it might be a mistake. :)  Thank you for the reply.
