### ISSUE TITLE
About test datasets

### ISSUE THREAD

**Issue by junhyukk** [InterDigitalInc/CompressAI#81]
First of all, thanks for your great work. 
I'm just wondering about the test datasets that you used for "results" folder.

1. 'clic2020-pro' means clic2020-professional test dataset having 60 images? Or it means valid dataset, which has 41 images? 
Could you elaborate the datasets in detail?

2. If the resolution of a test image cannot be divide by 64  (in the case of CLIC dataset), how can you use that image for evaluation? Because as far as I understand, the model (e.g., Cheng2020) can only process images whose resolution can be divided by 64.

**Comment by jbegaint** [comment]
Hi, 

1. we use the `test` sets for the CLIC datasets. Networks are trained on patches extracted from Vimeo90k. There are 250 images in the _professional_ subset and 178 in the _mobile_ one. You can find more information on the related [tensorflow dataset page](https://www.tensorflow.org/datasets/catalog/clic).
2. padding is applied, [see here](https://github.com/InterDigitalInc/CompressAI/blob/master/compressai/utils/eval_model/__main__.py#L81), in short you just need to make sure the image spatial dimensions are multiple of `2**(num_strides_2)`.
