### ISSUE TITLE
Question on license

### ISSUE THREAD

**Issue by xyq7** [InterDigitalInc/CompressAI#82]
Thanks for you excellent library.
Recently we develop new models with CompressAI and publish an academic paper on ACMMM 2021. We are preparing for releasing the source code. 
May we include the used codes with acknowledgement and reference to your library and follow your license?
Thanks.

**Comment by fracape** [comment]
Hi, this repo is currently under Apache v2.0 license, so yes, you can use it. Thanks for citing, the ref is in the readme.
