### ISSUE TITLE
Regarding the hyperdecoder architecture

### ISSUE THREAD

**Issue by Mikeyboiii** [InterDigitalInc/CompressAI#88]
## Implementation
Same question @soon0698 raised in issue #80 , I'm curious about the motive behind switching the last layer of hyperdecoders from deconv(as described in the original minnen18 paper) to conv? What is the essential difference between a stride 1 convolution and transposed convolution? And would a deconv at the last layer of hyperdecoders do the same? 
Thanks!

**Comment by fracape** [comment]
Hi. I don't think there is a difference when the stride is one and same padding: https://stackoverflow.com/questions/55107008/conv2d-and-conv2d-transpose-with-stride-1
Happy to merge a PR if you tried it and comment on results!

**Comment by fracape** [comment]
Closing this for now. Feel free to reopen or start a thread in the section discussion if it is not an issue (broken).
