### ISSUE TITLE
`mean_hat` is not used for `y_hat` in `JointAutoregressiveHierarchicalPriors` in the evaluation mode

### ISSUE THREAD

**Issue by fujibo** [InterDigitalInc/CompressAI#9]
I find that `mean_hat` is not considered for calculating `y_hat` at the `forward` function of `JointAutoregressiveHierarchicalPriors` in the evaluation mode.
https://github.com/InterDigitalInc/CompressAI/blob/master/compressai/models/priors.py#L476

`y_hat` should be calculated as `dequantize(quantize(y - mean_hat)) + mean_hat` in the evaluation mode.
It is also implemented in the `compress` function and `forward` in `MeanScaleHyperprior`.

**Comment by jbegaint** [comment]
yes, this is already performed in the GaussianConditionnal class
see https://github.com/InterDigitalInc/CompressAI/blob/a4ee35ec58c046863b1f9dabcaf9c3eba447a05c/compressai/entropy_models/entropy_models.py#L578 and https://github.com/InterDigitalInc/CompressAI/blob/a4ee35ec58c046863b1f9dabcaf9c3eba447a05c/compressai/entropy_models/entropy_models.py#L141

**Comment by jbegaint** [comment]
Hi! Sorry for the late reply.

Actually,  I can't decide which version is more "correct". Unless I'm missing something, in inference mode the means are still calculated from `quantize(y_i)` and not from `dequantize(quantize(y_i - mean_i)) + mean_i` (which is auto-regressively performed in `compress`). So I both cases, current code and your PR, the quantization is slightly off for `y_hat`.

**Comment by fujibo** [comment]
> Actually, I can't decide which version is more "correct".
I understand your consideration.
I will consider the current implementation as a program specification.
Please close my PR and this issue.

Thank you very much for your consideration.
