### ISSUE TITLE
Code about end-to-end video coding 

### ISSUE THREAD

**Issue by richardlzx** [InterDigitalInc/CompressAI#95]
Thank you very much for your contribution to deep learning data compression. I want to know if you plan to add end-to-end video compression code to compressai? Because many recent papers on end-to-end video compression are not open source, which is not conducive to beginners' entry

**Comment by fracape** [comment]
Hi, we started to push a video pipeline recently. We implemented the scale-space-flow model from Google and provided utils to bench with a couple of traditional codecs. Note that this is a beta version for now. Hopefully, other video models that perform better than conventional codecs will be brought here. Thanks.
