### ISSUE TITLE
About the results of the cheng-anchor and cheng-attn models

### ISSUE THREAD

**Issue by junhyukk** [InterDigitalInc/CompressAI#96]
First of all, thanks for your great work.

I'm wondering about the results of the 'cheng-anchor' and 'cheng-attn' models in the 'results' folder.
According to the reported RD performance, the 'cheng-anchor' model achieved better performance than the 'cheng-attn' model, which is the opposite results of the content of the paper. 

Did you upload the result in reverse? 
If not, could you explain why?

**Comment by fracape** [comment]
Hi! Good point, we have not found that the attention mechanism helped in our experiments. That seems to be inline with what other authors say [(WaveOne2021)](https://arxiv.org/pdf/2104.14335.pdf). The results were not uploaded in reverse. I'd be happy to look at it if somebody finds a problem with our implementation.
